apiVersion: v1
kind: Secret
metadata:
  name: fcg-games-secret
type: Opaque
stringData:
  ConnectionStrings__FCGUsersDbConnection: "${FCG_DB_CONNECTION_STRING}"
  NewRelic__LicenseKey: "${NEW_RELIC_LICENSE_KEY}"
  ElasticSearch__ApiKey: "${ELASTICSEARCH_API_KEY}"
  ElasticApm__SecretToken: "${ELASTIC_APM_SECRET_TOKEN}"
